apiVersion: apps/v1
kind: Deployment
metadata:
  name: fyp-grafana-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fyp-grafana
  template:
    metadata:
      labels:
        app: fyp-grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest
        ports:
        - containerPort: 3000
        env:
        - name: GF_SECURITY_ALLOW_EMBEDDING
          value: "true"
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "true"
        - name: GF_AUTH_ANONYMOUS_ORG_ROLE
          value: "Admin"
        - name: GF_PANELS_DISABLE_SANITIZE_HTML
          value: "true"
        securityContext:
          runAsUser: 472
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: fyp-grafana-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: fyp-grafana
  ports:
  - port: 80
    targetPort: 3000
