# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: photo.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'photo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bphoto.proto\"\"\n\x0cPhotoRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\"\'\n\rPhotoResponse\x12\x16\n\x0eprocessed_data\x18\x01 \x01(\x0c\x32<\n\x0ePhotoProcessor\x12*\n\x07Process\x12\r.PhotoRequest\x1a\x0e.PhotoResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'photo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PHOTOREQUEST']._serialized_start=15
  _globals['_PHOTOREQUEST']._serialized_end=49
  _globals['_PHOTORESPONSE']._serialized_start=51
  _globals['_PHOTORESPONSE']._serialized_end=90
  _globals['_PHOTOPROCESSOR']._serialized_start=92
  _globals['_PHOTOPROCESSOR']._serialized_end=152
# @@protoc_insertion_point(module_scope)
